import {StyleSheet} from 'react-native';

const estilos = StyleSheet . create({

   area: {
    borderWidth: 2,
    backgroundColor: 'white',
    borderColor: '#000',
    borderRadius: 20, 
    height:90,
    width: 140,
    
  },
  area2: {
    justifyContent: 'center',
    marginLeft: 20,
  },
  areatext3: {
    color: '#3299CC',
    fontSize: 20,
  },
  titletermo: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subTitletermo: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 5,
  },
  viewbuttontermo: {
    marginTop: '10%',
  },
  acceptContainertermo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginVertical: 10,
  },
  radioButtontermo: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  radioInnerCircletermo: {
    height: 12,
    width: 12,
    borderRadius: 6,
    backgroundColor: 'black',
  },
  acceptTexttermo: {
    fontSize: 22,
  },
  botoestermo: {
    width: 300,
    height: 45,
    backgroundColor: '#3299CC',
    borderWidth: 2,
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 5,
  },
  buttonTexttermo: {
    fontWeight: 'bold',
    alignSelf: 'center',
    color: 'white',
    fontSize: 20,
  },
  viewviewtermo: {
    width: '95%',
    height: 400,
    borderWidth: 2,
    marginTop: 25,
    borderColor: 'grey',
    alignSelf: 'center',
  },
  area3: {
    flexDirection: 'row',
    width: '95%',
    height: 90,
    marginTop: 40,
    marginLeft: 10, 
    marginBottom: -15,

  },
  fotoBotoes:{
    borderRadius:10,
    padding: 10, 
    margin: 5, 
    height: 80, 
    width: 80, 
    resizeMode: 'stretch', 
  },
  imagemFundo:{
    resizeMode: 'cover',
    width: '100%',
    height: '100%'
  },

  nameArea:{
    color:'#000000',
    fontSize: 25,
    fontWeight: 'bold',
    margin: 5,
   },

   textArea:{
     fontSize: 15,
     margin: 5,     
   },
  
  containerCima:{
    flexDirection:"row",
    height: 325,
    width: 325,
    alignSelf: 'center',
    marginTop: 60,
    flexWrap: 'wrap',

  },


  botaopicto:{
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex',
    backgroundColor:"#fff",
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 20,
    height:125,
    width:120,
    margin: 20, 
    alignSelf: 'center',
    padding: 5,
  },
  botaometa:{
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex',
    backgroundColor:"#fff",
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 20,
    height:125,
    width:120,
    margin: 20, 
    alignSelf: 'center',
    padding: 5,
  },
  botaopais:{
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex',
    backgroundColor:"#fff",
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 20,
    height:125,
    width:120,
    margin: 20, 
    alignSelf: 'center',
    padding: 5,
  },
  botaopet:{
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex',
    backgroundColor:"#fff",
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 20,
    height:125,
    width:120,
    margin: 20, 
    alignSelf: 'center',
    padding: 5,
  },

  botoesHome:{
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex',
    backgroundColor:"#fff",
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 20,
    height:125,
    width:125,
    margin: 20, 
    alignSelf: 'center',
    padding: 5,
  },

  textoBotoes:{
    fontSize: 18,
    textAlign: 'center',
  },
  viewfundos: {
    width: '100%',
    height: '100%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  trocarfundo:{
    width: 150,
    height: 80,
    borderWidth: 2,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  viewfundoss: {
    width: '85%',
    height: '45%',
    alignSelf: 'center',
    marginTop: 100,
    flexWrap: 'wrap',
    flexDirection: 'wrap',
  },
  botoesfundo: {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'flex',
  backgroundColor:"#fff",
  borderWidth: 1,
  borderColor: '#000',
  height:120,
  width:75, 
  alignSelf: 'center',
  marginVertical: 10,
  marginLeft: 25,
  
},
buttonF: {
  backgroundColor: '#3498db',
  padding: 10,
  borderRadius: 5,
},
buttonTextF: {
  color: 'white',
  fontSize: 18,
},
modalContainerF: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
},
modalButtonF: {
  marginBottom: 10,
},
imageF: {
  width: 100,
  height: 100,
},
closeButtonF: {
  backgroundColor: '#e74c3c',
  padding: 10,
  borderRadius: 5,
  marginTop: 20,
},
closeButtonTextF: {
  color: 'white',
  fontSize: 18,
},

})
export default estilos;